apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-visitor-chart.fullname" . }}
  labels:
    {{- include "flask-visitor-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-visitor-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-visitor-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: flask-visitor-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        {{- range .Values.env}}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.fullnameOverride }}
              key: postgres-password
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database | quote }}
          
