apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-visitor-chart.fullname" . }}
  labels:
    {{- include "flask-visitor-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "flask-visitor-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000